server:
  port: 1111
spring:
  security:
    basic:  enabled
eureka:
  instance:
    hostname: 127.0.0.1
  client:
  ######由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
  ######检索服务设置为false
    fetch-registry: false
    serviceUrl:
      defalutZone: http://${eureka.instance.hostname}:${server.port}/eureka/
