server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
     gateway:
       routes:
       - id: xujin_route
         uri: http://www.baidu.com:80/
         predicates:
         - Path=/baidu
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:1111/eureka/

